### PR TITLE
Master update

### PR DESCRIPTION
**Pull request by pps83**

### CODE REVIEW

**Comment by pps83** [comment]
FYI, after I updated I seem to be getting consistently slower runs by 5-10% in my test app that mainly spends its time decoding with `p4nzdec256v32`. Exe size is down by 200-300KB though.

I've done multiple runs, switchign back and forth between old and new versions and making many runs. I get consistently 7% slower results with updated build.

**Review by powturbo — APPROVED** [review]
Thanks for fixing

**Review by powturbo — APPROVED** [review]
Not sure why a declaration is missing. This is available in AVX.
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm256_extract_epi64&expand=3549,2431

**Review by powturbo — APPROVED** [review]
thank you for your contribution

**Comment by powturbo** [comment]
I've only replaced the zigzag macros with inline functions in the file bitunpack.c where p4nzdec256v32 is defined. Can you please check your compiler options?

**Comment by pps83** [comment]
> Not sure why a declaration is missing. This is available in AVX.
> https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm256_extract_epi64&expand=3549,2431

No, it's not. Check with clang: https://godbolt.org/z/3JtR8Y (try to comment out the define to see the result in `-m32` build)

**Comment by pps83** [comment]
> Can you please check your compiler options?

In both cases VS project files are identical, no compiler option changes.

**Comment by powturbo** [comment]
_mm256_extract_epi64: 
Ok, for 32 bits. I've not considered 32 bits in the last years.
p4nzdec256v32 :
 I'll benchmark p4nzdec256v32 with macros and with inline functions in the next days.

**Comment by pps83** [comment]
> _mm256_extract_epi64:
> Ok, for 32 bits. I've not considered 32 bits in the last years.

There is code for 32-bit specific builds. I use 64-bit, but often debugging works better with 32-bit builds.

> p4nzdec256v32 :
> I'll benchmark p4nzdec256v32 with macros and with inline functions in the next days.

Can you please tell me where I can update that macro and I'll let you know what the difference is in my case with and without the macro?

**Comment by powturbo** [comment]
Just convert mm_zzagd_epi32 in bitutil.h to a macro.

**Comment by pps83** [comment]
> Just convert mm_zzagd_epi32 in bitutil.h to a macro.

(found it, I had old version checked out as it performs better in my case)
From the code and from git log it's not even clear to what macro I'd need to change it.

**Comment by powturbo** [comment]
https://github.com/powturbo/TurboPFor/blob/master/bitutil.h#L71

replace the line 71 with:
#define mm_zzagd_epi32(v) _mm_xor_si128(_mm_srli_epi32(v,1), _mm_srai_epi32(_mm_slli_epi32(v,31),31) )

**Comment by pps83** [comment]
> https://github.com/powturbo/TurboPFor/blob/master/bitutil.h#L71

> https://github.com/powturbo/TurboPFor/blob/master/bitutil.h#L71
> 
> replace the line 71 with:
> #define mm_zzagd_epi32(v) _mm_xor_si128(_mm_srli_epi32(v,1), _mm_srai_epi32(_mm_slli_epi32(v,31),31) )

I tried it, and didn't get any noticeable difference. Seems the problem comes from some other change.

I run some code to verify results correctness and I log time, to see if any change accidentally introduces slower times. This is the log that I get with the test with latest TurboPFor: `1:755 done, totalReadTime:943553micro`

With old version I get this: `1:632 done, totalReadTime:808483micro`. Even if I re-run the test times change only within 1-2%, and when I switch to different version of TurboPFor I clearly and consistently get slower test results. The test reads large amount of data and does some computations to verify overall result correctness. the `totalReadTime` is the time it took to read that data from disk and decompress it (using TurboPFor), as you can see the time increased from 808.4ms to 943.5ms, also note, these timings include time that's spent in reading the files from filesystem (a few thousand files and around 500MB total). In other words, negative impact is likely way more than what I see percent wise.

**Pull request merged**
