### PR TITLE
Master merge fixes

### PR DESCRIPTION
**Pull request by pps83**
+ USE_SSE and USE_AVX2 aren't references anywhere now.
 + removed spurious whitespace changes in conf.h

### CODE REVIEW

**Comment by pps83** [comment]
conf.h appears as if it doesn't have changes because you've made almost the same change already

**Comment by powturbo** [comment]
I've included, myapp and mycpp as examples to show how to use turbopfor

**Review by powturbo — COMMENTED** [review]
myapp and mycpp should stay there as example

**Review by powturbo — APPROVED** [review]

**Comment by pps83** [comment]
> myapp and mycpp should stay there as example

updated

**Review by powturbo — APPROVED** [review]

**Review by powturbo — APPROVED** [review]

**Review by powturbo — APPROVED** [review]

**Pull request merged**
